FROM --platform=linux/x86_64 node:20

ENV ADDRESSR_ENABLE_GEO=${ADDRESSR_ENABLE_GEO}
ENV ADDRESSR_INDEX_TIMEOUT=${ADDRESSR_INDEX_TIMEOUT:-30s}
ENV ADDRESSR_INDEX_BACKOFF=${ADDRESSR_INDEX_BACKOFF:-1000}
ENV ADDRESSR_INDEX_BACKOFF_INCREMENT=${ADDRESSR_INDEX_BACKOFF_INCREMENT:-1000}
ENV ADDRESSR_INDEX_BACKOFF_MAX=${ADDRESSR_INDEX_BACKOFF_MAX:-10000}
ENV COVERED_STATES=${COVERED_STATES}
ENV ELASTIC_HOST=${ELASTIC_HOST}
ENV ELASTIC_PORT=${ELASTIC_PORT:-9200}
ENV NODE_OPTIONS=${NODE_OPTIONS}

RUN apt-get update && apt-get upgrade -y
RUN npm i -g @mountainpass/addressr

EXPOSE 8080
CMD addressr-server-2
